export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const SAVE_SHIPPING_DATA_CART= 'SAVE_SHIPPING_DATA_CART';
export const SAVE_PAYMENT_METHOD_CART ='SAVE_PAYMENT_METHOD_CART';
export const CART_EMPTY = 'CART_EMPTY';